db_file: "bot.db"

messages:
  responses:
    start_message: "Привет! Чтобы начать сохранять ссылки в своем Pocket аккаунте, для начала тебе необходимо дать мне на это доступ. Для этого переходи по ссылке:\n%s"
    saved_successfully: "Ссылка успешно сохранена!"
  errors:
    default: "Произошла неизвестная ошибка."
    invalid_url: "Это невалидная ссылка!"
    unable_to_save: "Увы, не удалось сохранить ссылку. Попробуй ещё раз позже."
    already_authorized: "Ты уже авторизирован. Присылай ссылку, а я её сохраню."
    unknown_command: "Я не знаю такой команды :("